/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.eventos_hyrule;

import com.eventos_hyrule.Vistas.RegistroActividadInternalFrame;
import com.eventos_hyrule.Vistas.RegistroEventoInternalFrame;
import com.eventos_hyrule.Vistas.RegistroParticipanteInternalFrame;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author sofia
 */
public class panelInicial extends javax.swing.JFrame {
    private JDesktopPane desktopPane;

    public panelInicial() {
        super("Sistema de Gestión de Eventos - Hyrule");
        initializeUI();
    }
private void initializeUI() {
        // Configuración básica de la ventana principal
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1000, 700);
        setLocationRelativeTo(null);

        // Crear el JDesktopPane
        desktopPane = new JDesktopPane();
        setContentPane(desktopPane);

        // Crear la barra de menú
        JMenuBar menuBar = new JMenuBar();
        
        // Menú Eventos
        JMenu menuEventos = new JMenu("Eventos");
        JMenuItem itemRegistroEvento = new JMenuItem("Registrar Evento");
        itemRegistroEvento.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                abrirVentanaRegistroEvento();
            }
        });
        menuEventos.add(itemRegistroEvento);
        
        // Menú Participantes
        JMenu menuParticipantes = new JMenu("Participantes");
        JMenuItem itemRegistroParticipante = new JMenuItem("Registrar Participante");
        itemRegistroParticipante.addActionListener(e -> abrirVentanaRegistroParticipante());
        menuParticipantes.add(itemRegistroParticipante);
        
        
        //Menu Actividades
        JMenu menuActividades = new JMenu("Actividades");
        JMenuItem itemRegistroActividad = new JMenuItem("Registrar Actividad");
        itemRegistroActividad.addActionListener(e -> abrirVentanaRegistroActividad());
        
        menuActividades.add(itemRegistroActividad);

        menuBar.add(menuEventos);
        menuBar.add(menuParticipantes);
        menuBar.add(menuActividades);
        setJMenuBar(menuBar);
    }


    private void abrirVentanaRegistroEvento() {
        RegistroEventoInternalFrame registroFrame = new RegistroEventoInternalFrame();
        desktopPane.add(registroFrame);
        registroFrame.setVisible(true);
        centrarVentanaInterna(registroFrame);
    }

    private void abrirVentanaRegistroParticipante() {
        RegistroParticipanteInternalFrame registroFrame = new RegistroParticipanteInternalFrame();
        desktopPane.add(registroFrame);
        registroFrame.setVisible(true);
        centrarVentanaInterna(registroFrame);
    }

    private void abrirVentanaRegistroActividad() {
        RegistroActividadInternalFrame registroFrame = new RegistroActividadInternalFrame();
        desktopPane.add(registroFrame);
        registroFrame.setVisible(true);
        centrarVentanaInterna(registroFrame);
    }    
    
    private void centrarVentanaInterna(JInternalFrame frame) {
        Dimension desktopSize = desktopPane.getSize();
        Dimension frameSize = frame.getSize();
        frame.setLocation((desktopSize.width - frameSize.width) / 2, 
                         (desktopSize.height - frameSize.height) / 2);
    }

    public static void main(String[] args) {
        // Verificar conexión a la base de datos
        conexionDB conexion = new conexionDB();
        conexion.Connect();

        // Mostrar la aplicación
        SwingUtilities.invokeLater(() -> {
            panelInicial app = new panelInicial();
            app.setVisible(true);
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
